name: check specfiles updates
on:
  # allow for manually running an workflow
  workflow_dispatch:

  schedule:
    - cron: "0 3 * * Sat"

permissions: {}

jobs:
  check-updates:
    name: check-updates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: aidandenlinger/autocopr@v1
        with:
          mode: check
